apiVersion: v1
kind: Pod
metadata:
  name: write-rbd-test
  labels:
    app: write-rbd
spec:
  securityContext:
    runAsNonRoot: true
    seccompProfile:
      type: RuntimeDefault  
  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
        - matchExpressions:
          - key: kubernetes.io/hostname
            operator: In
            values:
            - odf-416-new-4gwmc-worker-0-n5h7d 
  containers:
    - name: filler
      image: registry.redhat.io/ubi8/ubi-minimal
      command:
        - /bin/sh
        - -c
      args:
        - dd if=/dev/urandom of=/mnt/rbd/test-file bs=1G count=5; sleep 86400
      volumeMounts:
        - name: rbd-test
          mountPath: /mnt/rbd
  volumes:
    - name: rbd-test
      persistentVolumeClaim:
        claimName: rbd-storage
  restartPolicy: Always
